### ISSUE TITLE
小视频不够清晰，怎么办？求教

### ISSUE THREAD

**Issue by lifengios** [LingLemon/XFAVFoundation#1]

**Comment by LINGLemon** [comment]
代码中bitsPerSecond我设置为12，你可以设置高一点。可是要注意，越清晰，视频越大，按照现在的配置，10s的视频在2.8m

**Comment by LingLemon** [comment]
代码中bitsPerSecond我设置为12，你可以设置高一点。可是要注意，越清晰，视频越大，按照现在的配置，10s的视频在2.8m
