### ISSUE TITLE
iPhoneX问题

### ISSUE THREAD

**Issue by Zws-China** [LingLemon/XFAVFoundation#10]
您好，拍摄视屏和预览视屏我看您设置的填充模式都是AVLayerVideoGravityResizeAspect，在使用iPhone X拍摄（拍摄没有全屏）之后，播放却成了全屏，并且视屏被切割了（相当于AVLayerVideoGravityResizeAspectFill）。不知道是什么问题。

**Comment by LINGLemon** [comment]
啊哈哈，终于有人提这个问题了= =我知道这个问题可是没办法调试（因为公司没买iPhone X），你QQ多少我加你一下

**Comment by LINGLemon** [comment]
我大概知道要改哪里可是不知道对不对，你加我一下QQ：396955213，我们一起解决看看
