### ISSUE TITLE
录制小视频奔溃

### ISSUE THREAD

**Issue by chengzj456** [LingLemon/XFAVFoundation#11]
报错原因：
-[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first
(null)
偶发 无法复现出来～

**Comment by LINGLemon** [comment]
应该是异步录制小视频的问题，以前一直是同步录制的后来在这里改成异步录制如果不崩溃的话我就在公司项目也这样改，看来还是不行所以现在我又改成同步了= =

**Comment by chengzj456** [comment]
所以要怎么改~~我看你更新后的代码和我本地的是一样的！！！是同步录制

**Comment by LINGLemon** [comment]
一样的话，那就不用改了= =

**Comment by chengzj456** [comment]
qa已经测试奔溃2-3次了！！！ 蛋疼

**Comment by HikingMan** [comment]
![image](https://user-images.githubusercontent.com/13775067/132307449-2c987726-bfd7-4192-b23b-fa99cd292f4a.png)
这里延时0.3s之后执行是不是有问题，应该在finishWritingWithCompletionHandler的回调里面去处理。有可能上次的finishWritingWithCompletionHandler在0.3s内没有执行，又去下一次录制，然后canWrite就会为YES。
![image](https://user-images.githubusercontent.com/13775067/132307939-b8fb684a-5ba7-45fd-afcc-b58096d0beda.png)
这里就不会执行，从而崩溃
