### ISSUE TITLE
学习了,现在很多都要求加入暂停功能,可以实现么?

### ISSUE THREAD

**Issue by OldCaptain** [LingLemon/XFAVFoundation#2]
学习了,现在很多都要求加入暂停功能,可以实现么?

**Comment by LingLemon** [comment]
这个我没有仔细研究，因为业务没有这个需求，你可以百度一下AVAssetWriter的demo看看，或者AVAssetWriter 暂停录制 去百度搜一下

**Comment by LINGLemon** [comment]
这个我没有仔细研究，因为业务没有这个需求，你可以百度一下AVAssetWriter的demo看看，或者AVAssetWriter 暂停录制 去百度搜一下

**Comment by OldCaptain** [comment]
恩  等我去研究研究 谢谢
