### ISSUE TITLE
iOS13点击确认后没有响应的临时解决办法

### ISSUE THREAD

**Issue by HankMonster** [LingLemon/XFAVFoundation#22]
升级到iOS13后拍照或者视频后点击确认按钮没有相应。原因是`savePhotoWithImage`这个方法在保存到系统相册后，在将照片复制到自定义相册的时候，不知道什么原因出错了。临时的解决方案就是只保存到系统相册，注释掉自定义相册的逻辑

![image](https://user-images.githubusercontent.com/36218911/65658904-2a221300-e05c-11e9-9a05-6e2c5dd73da3.png)

**Comment by beibeiaiwuhao** [comment]
你好，请问现在还有什么其他解决办法吗？

**Comment by xubillde** [comment]
iOS13 注释掉自定义相册的逻辑
iOS14 处理拍照时的线程问题，必须主线程，才能界面消失
