### ISSUE TITLE
写入视频和音频的时候是主线程，为什么不用子线程呢

### ISSUE THREAD

**Issue by frankkay** [LingLemon/XFAVFoundation#4]

**Comment by LINGLemon** [comment]
曾经是弄了一个队列搞了个线程专门进行录制的。后来查到录制小视频会有概率崩溃，之后就移除了。现在崩溃是不见了，可是现在公司项目忙，要搞Mac开发就不再看这个了。好像我看了官方文档，这个录制好像它自己就是在子线程弄的
