### ISSUE TITLE
调用系统相册后拍照会崩溃

### ISSUE THREAD

**Issue by jizhengzhu** [LingLemon/XFAVFoundation#5]
非常感谢大神的分享，我发现把XFAVFoundation和XFPhotoLibraryManager两个文件拖到自己的项目里可以成功调用相机，也可以正常拍摄视频和照片，但是如果我在项目中调用UIImagePickerController系统相册后，再次调用XFCameraController拍照时会崩溃，崩溃定位到takePhotos方法，根据设备输出获得连接时，captureConnection为空值，    //根据设备输出获得连接
    AVCaptureConnection *captureConnection = [self.captureStillImageOutput connectionWithMediaType:AVMediaTypeVideo];
请问大神，这种情况怎么办啊？

**Comment by LINGLemon** [comment]
是不是你的UIImagePickerController的对象占用了这个captureConnection资源所以这个方法就不返回captureConnection了？
