### ISSUE TITLE
录制中的一些问题和权限问题

### ISSUE THREAD

**Issue by iucry** [LingLemon/XFAVFoundation#7]
如果录制时间不是很长显示不出   保存和取消按钮
如果授权开始不同意崩了，后来在设置中给了授权还是会出问题崩溃

**Comment by LINGLemon** [comment]
你确定有这个问题？

**Comment by LINGLemon** [comment]
请留一下你的手机型号，系统号

**Comment by iucry** [comment]
手机型号：5s   系统是：9.2

**Comment by LINGLemon** [comment]
新的你试试看，se是可以的，5s没试过，不过这个是用在我公司项目里面，不应该有问题才是

**Comment by LINGLemon** [comment]
不在现场不知道你遇到了什么，这个项目我们公司测试组测过的，各个iOS版本也测试过没问题，线上使用也有几个月了，所以不知道你为什么会遇到这样的问题。话说自己调试看看问题所在吧，解决了分享一下~

**Comment by LINGLemon** [comment]
没重现
