### ISSUE TITLE
视频拍摄调整焦距后，拍摄出来的视频还是1.0的焦距

### ISSUE THREAD

**Issue by chengzj456** [LingLemon/XFAVFoundation#9]
if (scale < self.videoInput.device.activeFormat.videoMaxZoomFactor && scale>1)
        [self changeDeviceProperty:^(AVCaptureDevice *captureDevice) {
            [captureDevice rampToVideoZoomFactor:scale withRate:10];
        }];
我添加了这句 也无效

**Comment by LINGLemon** [comment]
是啊，视频调焦距这个功能我没能实现= =

**Comment by Henry519** [comment]
这个问题我解决了，在捏合手势代理里面添加如下代码：

if (allTouchesAreOnTheCaptureVideoPreviewLayer) {

        CGFloat maxScaleAndCropFactor = 10;
        if (self.beginGestureScale * recognizer.scale > 1.0 && self.beginGestureScale * recognizer.scale < maxScaleAndCropFactor)
        {
             self.effectiveScale = self.beginGestureScale * recognizer.scale;
            if (self.effectiveScale < self.videoInput.device.activeFormat.videoMaxZoomFactor && self.effectiveScale>1)
                [self changeDeviceProperty:^(AVCaptureDevice *captureDevice) {
                    [captureDevice rampToVideoZoomFactor:self.effectiveScale withRate:10];
                }];
        }
    }

亲测OK

**Comment by LINGLemon** [comment]
好的，谢谢你

**Comment by LINGLemon** [comment]
新代码已提供这个功能的支持，你看看
